/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author mateu
 */
public class Tela_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_cadastro
     */
    public Tela_cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcep = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtdata = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtbairro = new javax.swing.JTextField();
        txtedereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnsalvar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtsenha = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(239, 151, 1));
        jPanel2.setLayout(null);

        txtcep.setBackground(new java.awt.Color(255, 255, 255));
        txtcep.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txtcep);
        txtcep.setBounds(380, 80, 200, 30);

        txtnome.setBackground(new java.awt.Color(255, 255, 255));
        txtnome.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txtnome);
        txtnome.setBounds(130, 80, 200, 30);

        txtemail.setBackground(new java.awt.Color(255, 255, 255));
        txtemail.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txtemail);
        txtemail.setBounds(130, 150, 200, 30);

        txtdata.setBackground(new java.awt.Color(255, 255, 255));
        txtdata.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txtdata);
        txtdata.setBounds(130, 290, 200, 30);

        txttel.setBackground(new java.awt.Color(255, 255, 255));
        txttel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txttel);
        txttel.setBounds(380, 290, 200, 30);

        txtbairro.setBackground(new java.awt.Color(255, 255, 255));
        txtbairro.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txtbairro);
        txtbairro.setBounds(380, 220, 200, 30);

        txtedereco.setBackground(new java.awt.Color(255, 255, 255));
        txtedereco.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jPanel2.add(txtedereco);
        txtedereco.setBounds(380, 150, 200, 30);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel1.setText("TELEFONE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(380, 270, 160, 20);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel2.setText("NOME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 60, 160, 20);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel3.setText("E-MAIL");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(130, 130, 160, 20);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel4.setText("SENHA");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 200, 160, 20);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel5.setText("DATA DE NASCIMENTO ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(130, 270, 160, 20);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel6.setText("CEP");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(380, 60, 160, 20);

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel7.setText("ENDERECO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(380, 130, 160, 20);

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel8.setText("BAIRRO");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(380, 200, 160, 20);

        btnsalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnsalvar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnsalvar.setText("CADASTRAR");
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalvar);
        btnsalvar.setBounds(300, 350, 100, 30);

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel9.setText("JA TEM CONTA ? ENTRAR");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(280, 380, 140, 15);

        txtsenha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtsenha);
        txtsenha.setBounds(130, 220, 200, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Telas/PIZZA.PNG"))); // NOI18N
        jPanel2.add(jLabel10);
        jLabel10.setBounds(500, 340, 120, 90);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(717, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        try {

            //CAMINHO PARA A CLASS
            Class.forName("com.mysql.cj.jdbc.Driver");
            //CONECXAO COM BANCO 
            Connection conectado = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_pizzaria", "root", "5821");
            //DEFINE O COMANDO PARA INSERIR NO BANCO 
            PreparedStatement st = conectado.prepareStatement("insert into tblcliente values(?,?,?,?,?,?,?,?);");

            //COMPLETA O COMANDO INSERT 
            st.setString(1, txtnome.getText());
            st.setString(2, txtemail.getText());
            st.setString(3, txtsenha.getText());
            st.setString(4, txtdata.getText());
            st.setString(5, txtcep.getText());
            st.setString(6, txtedereco.getText());
            st.setString(7, txtbairro.getText());
            st.setString(8, txttel.getText());


            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "cadastrado com sucesso");
            txtnome.setText("");
            txtemail.setText("");
            txtsenha.setText("");
            txtdata.setText("");
            txtcep.setText("");
            txtedereco.setText("");
            txtbairro.setText("");
            txttel.setText("");

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnsalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtbairro;
    private javax.swing.JTextField txtcep;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtedereco;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnome;
    private javax.swing.JPasswordField txtsenha;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
